name: Android CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: 17
  ANDROID_API_LEVEL: 34
  ANDROID_BUILD_TOOLS: 34.0.0
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

jobs:
  build:
    name: Build, Test & Upload APK
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            platform-tools
            build-tools;34.0.0
            platforms;android-34
            extras;google;m2repository
            extras;android;m2repository

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=8.5

      - name: Resolve dependencies
        run: ./gradlew dependencies

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: android-app-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Test Report (HTML)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/index.html
